
-- SQL Schema for AI Chat Application
-- Auto-generated by ChatGPT

CREATE TABLE res_company (
    id SERIAL PRIMARY KEY,
    company_name VARCHAR NOT NULL
);

CREATE TABLE dashboard_user (
    id SERIAL PRIMARY KEY,
    email VARCHAR UNIQUE NOT NULL,
    full_name VARCHAR NOT NULL,
    role VARCHAR NOT NULL,
    hashed_password VARCHAR NOT NULL,
    is_active BOOLEAN,
    is_superadmin BOOLEAN,
    profile_photo_url VARCHAR
);

CREATE TABLE dashboard_user_company_access (
    id SERIAL PRIMARY KEY,
    dashboard_user_id INTEGER NOT NULL REFERENCES dashboard_user(id),
    company_id INTEGER NOT NULL REFERENCES res_company(id)
);

CREATE TABLE res_partner (
    partner_id SERIAL PRIMARY KEY,
    active BOOLEAN,
    display_name VARCHAR,
    vat VARCHAR,
    ref VARCHAR,
    function VARCHAR,
    email VARCHAR,
    phone VARCHAR,
    mobile VARCHAR,
    whatsapp_phone VARCHAR,
    street VARCHAR,
    street2 VARCHAR,
    city VARCHAR,
    zip VARCHAR,
    nepa_customer_type VARCHAR,
    is_company BOOLEAN,
    create_date TIMESTAMP,
    write_date TIMESTAMP,
    partner_latitude DOUBLE PRECISION,
    partner_longitude DOUBLE PRECISION,
    nepa_last_invoice_date DATE,
    prime_ship_type VARCHAR,
    nepa_unreconciled_payments DOUBLE PRECISION,
    nepa_customer_credit DOUBLE PRECISION,
    state_id INTEGER,
    country_id INTEGER,
    create_uid INTEGER,
    write_uid INTEGER,
    user_id INTEGER,
    team_id INTEGER,
    property_product_pricelist INTEGER
);

CREATE TABLE utm_campaign (
    id SERIAL PRIMARY KEY,
    active BOOLEAN,
    title VARCHAR,
    quotation_count INTEGER,
    invoiced_amount DECIMAL(18,2),
    click_count INTEGER,
    is_auto_campaign BOOLEAN,
    user_id INTEGER,
    stage_id INTEGER,
    company_id INTEGER,
    create_date TIMESTAMP,
    write_date TIMESTAMP
);

CREATE TABLE account_account (
    id SERIAL PRIMARY KEY,
    code VARCHAR,
    name VARCHAR,
    account_type VARCHAR,
    deprecated BOOLEAN,
    create_date TIMESTAMP,
    write_date TIMESTAMP,
    company_id INTEGER,
    create_uid INTEGER,
    write_uid INTEGER
);

CREATE TABLE account_journal (
    id SERIAL PRIMARY KEY,
    name VARCHAR,
    code VARCHAR,
    active BOOLEAN,
    journal_type VARCHAR,
    default_account_id INTEGER REFERENCES account_account(id),
    company_id INTEGER,
    create_date TIMESTAMP,
    write_date TIMESTAMP,
    create_uid INTEGER,
    write_uid INTEGER
);

CREATE TABLE account_move (
    id SERIAL PRIMARY KEY,
    invoice_date DATE,
    create_date TIMESTAMP,
    write_date TIMESTAMP,
    delivery_date DATE,
    name VARCHAR,
    payment_reference VARCHAR,
    state VARCHAR,
    payment_state VARCHAR,
    ref VARCHAR,
    move_type VARCHAR,
    invoice_origin VARCHAR,
    nepa_shipped_by_nepa BOOLEAN,
    nepa_is_shipped BOOLEAN,
    is_delivery BOOLEAN,
    nepa_shpping_amount DOUBLE PRECISION,
    amount_commission DOUBLE PRECISION,
    amount_commission_discount DOUBLE PRECISION,
    amount_commission_shipping DOUBLE PRECISION,
    net_commission DOUBLE PRECISION,
    amount_untaxed_signed DOUBLE PRECISION,
    amount_tax_signed DOUBLE PRECISION,
    amount_total_signed DOUBLE PRECISION,
    amount_residual_signed DOUBLE PRECISION,
    prime_tracking_code INTEGER,
    prime_tracking_no VARCHAR,
    campaign_id INTEGER REFERENCES utm_campaign(id),
    medium_id INTEGER,
    source_id INTEGER,
    partner_id INTEGER REFERENCES res_partner(partner_id),
    company_id INTEGER,
    invoice_user_id INTEGER,
    nepa_sales_person_id INTEGER,
    team_id INTEGER,
    journal_id INTEGER REFERENCES account_journal(id),
    partner_bank_id INTEGER
);

CREATE TABLE account_move_line (
    id SERIAL PRIMARY KEY,
    account_move_id INTEGER REFERENCES account_move(id),
    product_id INTEGER REFERENCES product_product(id),
    standard_price DOUBLE PRECISION,
    quantity DOUBLE PRECISION,
    price_unit DOUBLE PRECISION,
    price_subtotal DOUBLE PRECISION,
    nepa_cogs_price DOUBLE PRECISION,
    discount DOUBLE PRECISION,
    price_commission DOUBLE PRECISION,
    account_id INTEGER REFERENCES account_account(id),
    debit DOUBLE PRECISION,
    credit DOUBLE PRECISION,
    balance DOUBLE PRECISION,
    amount_residual DOUBLE PRECISION,
    amount_currency DOUBLE PRECISION
);

CREATE TABLE product_product (
    id SERIAL PRIMARY KEY,
    active BOOLEAN,
    allow_out_of_stock_order BOOLEAN,
    display_name VARCHAR,
    barcode VARCHAR,
    detailed_type VARCHAR,
    invoice_policy VARCHAR,
    create_date TIMESTAMP,
    write_date TIMESTAMP,
    lst_price DOUBLE PRECISION,
    is_published BOOLEAN,
    purchase_ok BOOLEAN,
    sale_ok BOOLEAN,
    can_be_expensed BOOLEAN,
    product_commission_type VARCHAR,
    qty_available DOUBLE PRECISION,
    show_availability BOOLEAN,
    type VARCHAR,
    virtual_available DOUBLE PRECISION,
    categ_id INTEGER,
    product_tmpl_id INTEGER,
    website_id INTEGER
);

CREATE TABLE stock_quant (
    id SERIAL PRIMARY KEY,
    quantity DOUBLE PRECISION,
    reserved_quantity DOUBLE PRECISION,
    create_date TIMESTAMP,
    write_date TIMESTAMP,
    product_id INTEGER REFERENCES product_product(id),
    company_id INTEGER,
    location_id INTEGER,
    location_name VARCHAR,
    location_display_name VARCHAR,
    location_usage VARCHAR
);

CREATE TABLE stock_warehouse (
    id SERIAL PRIMARY KEY,
    active BOOLEAN,
    code VARCHAR,
    name VARCHAR,
    create_date TIMESTAMP,
    write_date TIMESTAMP,
    create_uid INTEGER,
    write_uid INTEGER,
    lot_stock_id INTEGER,
    partner_id INTEGER REFERENCES res_partner(partner_id),
    company_id INTEGER
);

CREATE TABLE pricelist (
    id SERIAL PRIMARY KEY,
    pricelist_name VARCHAR,
    pricelist_id INTEGER,
    pricelist_applied_on VARCHAR,
    pricelist_product_id INTEGER,
    product_sales_price DOUBLE PRECISION,
    start_date DATE,
    end_date DATE,
    product_template_external_id VARCHAR,
    product_template_id INTEGER,
    product_variant_external_id VARCHAR,
    product_variant_id INTEGER
);

CREATE TABLE pricelist_inventory (
    product_variant_id INTEGER PRIMARY KEY,
    product_template_id INTEGER,
    product_template_name VARCHAR,
    product_variant_name VARCHAR,
    product_barcode VARCHAR
);

CREATE TABLE journal_items (
    id SERIAL PRIMARY KEY,
    move_id INTEGER,
    move_name VARCHAR,
    journal_id INTEGER,
    journal_type VARCHAR,
    journal_name VARCHAR,
    company_id INTEGER,
    parent_state VARCHAR,
    date DATE,
    ref VARCHAR,
    account_id INTEGER,
    account_name VARCHAR,
    name VARCHAR,
    debit DOUBLE PRECISION,
    credit DOUBLE PRECISION,
    balance DOUBLE PRECISION,
    partner_id INTEGER,
    amount_residual DOUBLE PRECISION,
    reconciled BOOLEAN,
    create_uid INTEGER,
    write_uid INTEGER,
    create_date TIMESTAMP,
    write_date TIMESTAMP
);
